<?php

namespace RSHub\MarketplaceBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * ModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificationRepository extends EntityRepository {

	public function getWithCategories(array $nom_categories) {
		$qb = $this->createQueryBuilder('a');

		// On fait une jointure avec l'entité Categorie, avec pour alias « c »
		$qb->join('a.categories', 'c')
				->where($qb->expr()
						->in('c.name', $nom_categories)); // Puis on filtre sur le nom des catégories à l'aide d'un IN

		// Enfin, on retourne le résultat
		return $qb->getQuery()
				->getResult();
	}
	public function getWithCategoriesOrdered(array $nom_categories, $orderCol, $order) {
		$qb = $this->createQueryBuilder('a');

		// On fait une jointure avec l'entité Categorie, avec pour alias « c »
		$qb->join('a.categories', 'c')
				->where($qb->expr()
						->in('c.name', $nom_categories));
		$qb->add('orderBy', 'a.'.$orderCol.' '.$order);

		// Enfin, on retourne le résultat
		return $qb->getQuery()
				->getResult();
	}
	public function getByDownloads(array $nom_categories) {
		return $this->getWithCategoriesOrdered($nom_categories, 'downloads', 'DESC');
	}
	public function getByPopularity(array $nom_categories) {
		return $this->getWithCategoriesOrdered($nom_categories, 'stars', 'DESC');
	}
	public function getByNewest(array $nom_categories) {
		return $this->getWithCategoriesOrdered($nom_categories, 'date', 'DESC');
	}
	public function getByOldest(array $nom_categories) {
		return $this->getWithCategoriesOrdered($nom_categories, 'date', 'ASC');
	}
	public function getByName(array $nom_categories) {
		return $this->getWithCategoriesOrdered($nom_categories, 'name', 'ASC');
	}
}
