<?php

namespace RSHub\MarketplaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificationRepository extends EntityRepository
{
}
